config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  devise_for :users
  
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy] do
      resources :comment_replies, only: [:create, :destroy]
    end
  end
  
  resources :users, only: [:index,:show,:edit,:update] do
    member do
      get :follows, :followers
    end
      resource :relationships, only: [:create, :destroy]
  end
  
  get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  has_many :comment_replies, dependent: :destroy
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = @book.id
    @comment.save
    # redirect_to book_path(book)
  end

  def destroy
    @book = Book.find(params[:book_id])
    BookComment.find(params[:id]).destroy
    # redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
  
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_book_comment.html.erb
<table class='table table-sm'>
  <tbody>

    <% book.book_comments.each do |book_comment| %>

      <tr>
        <td><%= link_to(book.user) do %>
        <%= image_tag book_comment.user.get_profile_image, size:'50x50' %><br>
        <%= book_comment.user.name %>
        <% end %>
        </td>
        <td><%= book_comment.comment %>
        </td>
        <td>
          <% if book_comment.user == current_user %>
            <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-sm btn-danger", remote: true %>
          <% end %>
        </td>
      </tr>

<% end %>

  </tbody>
</table>

app/views/book_comments/_count.html.erb
コメント数: <%= book.book_comments.count %>

app/views/book_comments/_form.html.erb
<%= form_with model: [book, book_comment], local: false do |f| %>
  <%= f.text_area :comment, rows: '5', placeholder: "", class: "form-control comment_textarea" %>
  <%= f.submit "送信" %>
<% end %>

app/views/book_comments/create.js.erb
$("#comment_counter").html("<%= j(render "book_comments/count", book: @book) %>");
$("#comment_index").html("<%= j(render "book_comments/book_comment", book: @book) %>");
$('.comment_textarea').val("");

app/views/book_comments/destroy.js.erb
$('#comment_counter').html("<%= j(render 'book_comments/count', book: @book) %>");
$('#comment_index').html("<%= j(render 'book_comments/book_comment', book: @book) %>");